/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed
 */
public class BusStaion extends javax.swing.JFrame {

    /**
     * Creates new form BusStaion
     */
        Manager manager = new Manager();
        Vehicle vehicle1 = new Vehicle(10);
        Vehicle vehicle2 = new Vehicle(10);
        Vehicle vehicle3 = new Vehicle(10);
        
        
        //Trip trip1 = new Trip("Alexandria", "Cairo", 2, 3, "a001", "123");
        //Trip trip2 = new Trip("Alexandria", "Cairo", 2, 3, "a002", "123");
        //Trip trip3= new Trip("Alexandria", "Cairo", 2, 3, "a003", "123");
       
    CustomerGUI customerGui = new CustomerGUI();
    
        
    public BusStaion() {
        initComponents();
    }
    
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 556));
        setPreferredSize(new java.awt.Dimension(800, 556));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/multiple-users-silhouette.png"))); // NOI18N
        jButton3.setText("Customer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 10, 160, 100);

        jButton2.setBackground(new java.awt.Color(218, 236, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/manager (1).png"))); // NOI18N
        jButton2.setText("Manager");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 120, 160, 110);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/bus-station-vector-flat-background-illustration-eps-61688629.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 550);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(530, 170, 240, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //trip1.setVehicle(vehicle1);
        //trip2.setVehicle(vehicle2);
        //trip3.setVehicle(vehicle3);
        //manager.getListOfTrips().add(trip1);
        //manager.getListOfTrips().add(trip2);
        //manager.getListOfTrips().add(trip3);

        MyFilesManagement myFilesManagement = new MyFilesManagement();
        myFilesManagement.readFiles();
        incrementNumberOfSeatsTakenInEachVehicle();

        DefaultTableModel model = (DefaultTableModel) customerGui.getTripsTable().getModel();
        for(int i = 0; i < manager.getListOfTrips().size() ; i++){
            model.addRow(new Object[]{manager.getListOfTrips().get(i).getLocationFrom(),
                manager.getListOfTrips().get(i).getDestination(),manager.getListOfTrips().get(i).getDuration(),
                manager.getListOfTrips().get(i).getNumberOfStops(),manager.getListOfTrips().get(i).getCodeName(),
                manager.getListOfTrips().get(i).getVehicle().getNumberOfSeats(),
                manager.getListOfTrips().get(i).getVehicle().getNumberOfSeatsTaken()
                ,manager.getListOfTrips().get(i).getDate(),manager.getListOfTrips().get(i).getPrice(),
            manager.getListOfTrips().get(i).getDriverId()});
        }
        customerGui.setVisible(true);
        customerGui.getjPanel1().setVisible(false);
        this.setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // trip1.setVehicle(vehicle1);
        //trip2.setVehicle(vehicle2);
        //trip3.setVehicle(vehicle3);
        //manager.getListOfTrips().add(trip1);
        //manager.getListOfTrips().add(trip2);
        //manager.getListOfTrips().add(trip3);
        MyFilesManagement myFilesManagement = new MyFilesManagement();
        myFilesManagement.readFiles();
        incrementNumberOfSeatsTakenInEachVehicle();
        ManagerGUI managerGUI = new ManagerGUI();
        managerGUI.setVisible(true);
        this.setVisible(false);
        managerGUI.getjPanel1().setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusStaion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusStaion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusStaion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusStaion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        

        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusStaion().setVisible(true);
            }
        });
    }
    public static void incrementNumberOfSeatsTakenInEachVehicle()
    {
        for (int i = 0; i < Manager.getListOfTrips().size(); i++) {
            Trip trip = Manager.getListOfTrips().get(i);
            //System.out.println("***************************");
            //System.out.println(trip);
            Vehicle vehicle = trip.getVehicle();
            for (int j = 0; j < trip.getCustomerList().size() ; j++) {
                Customer customer = trip.getCustomerList().get(j);
                vehicle.increaseSeatsTaken( customer.getNumOfSeats() );
                //System.out.println(customer);
            }
            //System.out.println("***************************");
        }
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
