/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed
 */
public class CustomerGUI extends javax.swing.JFrame {
    
    
    /**
     * Creates new form CustomerGUI
     */
    public CustomerGUI() {
        initComponents();
        jButton4.setEnabled(false);
    }
    Manager manager = new Manager();
    Customer customer = new Customer();
    
    
    
    MyFilesManagement myFilesManagement = new MyFilesManagement();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tripsTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        numOfSeatsField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        firstNameField = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        newPriceField = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tripsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "To", "Duration", "Stops", "Trip code", "Available", "Taken", "Date", "Price", "Driver ID"
            }
        ));
        jScrollPane1.setViewportView(tripsTable);

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter trip code");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("View Ticket");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("First name");

        jLabel3.setText("Last name");

        jLabel4.setText("Phone number");

        jLabel5.setText("Age");

        jLabel6.setText("Number of seats");

        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        phoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberFieldActionPerformed(evt);
            }
        });

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Round Trip");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lastNameField)
                            .addComponent(phoneNumberField)
                            .addComponent(ageField)
                            .addComponent(numOfSeatsField)
                            .addComponent(firstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(newPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jButton2)
                        .addGap(16, 191, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numOfSeatsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPriceField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton6.setText("Sort");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(188, 188, 188)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        myFilesManagement.printToFiles();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        manager.getListOfTrips().clear();
        BusStaion busStaion = new BusStaion();
        this.setVisible(false);
        busStaion.setVisible(true);
        for(int i = 0;i<manager.getListOfVehicles().size();i++)
            manager.getListOfVehicles().get(i).setNumberOfSeatsTaken(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean success = true;
        customer = new Customer();
        String code = jTextField1.getText();

        try{
            customer.setCodeName(code);
            customer.setAge(Integer.parseInt(ageField.getText()));
            customer.setFirstName(firstNameField.getText());
            customer.setLastName(lastNameField.getText());
            
            if( !(firstNameField.getText().chars().allMatch(Character::isLetter)) || !(lastNameField.getText().chars().allMatch(Character::isLetter)))
            {
                throw new Exception();
            }
            
            customer.setNumOfSeats(Integer.parseInt(numOfSeatsField.getText()));
            customer.setPhoneNumber(phoneNumberField.getText());
            Double.parseDouble(phoneNumberField.getText());
            //customer.setRoundTrip(false);
            customer.setRoundTrip(jRadioButton1.isSelected());
            int i = manager.findTrip(code);
            boolean x = customer.bookTicket(manager.getListOfTrips().get(i));
            if(!x)
                JOptionPane.showMessageDialog(null, "Not enough seats");
            if( success )
            {
                firstNameField.setText("");
                ageField.setText("");
                lastNameField.setText("");
                phoneNumberField.setText("");
                numOfSeatsField.setText("");
                jTextField1.setText("");
                jPanel1.setVisible(false);
                JOptionPane.showMessageDialog(null, "Sucess!");
                for(int count = 0 ; count < 3 ; count++)
                {
                    DefaultTableModel model = (DefaultTableModel) tripsTable.getModel();
                    if(tripsTable.getValueAt(count, 4).equals(code)){
                        tripsTable.setValueAt(manager.getListOfTrips().get(i).getVehicle().getNumberOfSeatsTaken(), count, 6);
                        }
                }
                jButton4.setEnabled(true);
            }
        }
        catch(NumberFormatException e)
        {
            success = false;
            JOptionPane.showMessageDialog(null, "Phone number & age must contain digits only");
        }
        catch(ArrayIndexOutOfBoundsException e)
        {
            success = false;
            JOptionPane.showMessageDialog(null, "Trip not found.\nEnter correct code name.");
        }
        
        catch(Exception e)
        {
            success = false;
            JOptionPane.showMessageDialog(null, "Wrong format");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void phoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            TicketGUI ticketGUI = new TicketGUI();
            ticketGUI.setVisible(true);
            makeTicket(customer , jRadioButton1.isSelected());
            //ImageIcon newIcon = new ImageIcon("C:\\Users\\Ahmed\\Documents\\NetBeansProjects\\test\\ticket.jpg");
            ImageIcon newIcon = new ImageIcon("ticket.jpg");
            newIcon.getImage().flush();
            ticketGUI.getjLabel2().setIcon(newIcon);
        }
        catch(Exception e){
            System.out.println("no customer yet");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jPanel1.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        /*int i = manager.findTrip(customer);
        customer.setRoundTrip(true);
        newPriceField.setText(String.format("%s", manager.getListOfTrips().get(i).calculateRoundTripPrice()));*/
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tripsTable.getModel();
        model.setRowCount(0);
        Manager.getListOfTrips().sort(Trip::compare);
                for(int i = 0; i < manager.getListOfTrips().size() ; i++){
            model.addRow(new Object[]{manager.getListOfTrips().get(i).getLocationFrom(),
                manager.getListOfTrips().get(i).getDestination(),manager.getListOfTrips().get(i).getDuration(),
                manager.getListOfTrips().get(i).getNumberOfStops(),manager.getListOfTrips().get(i).getCodeName(),
                manager.getListOfTrips().get(i).getVehicle().getNumberOfSeats(),
                manager.getListOfTrips().get(i).getVehicle().getNumberOfSeatsTaken()
                ,manager.getListOfTrips().get(i).getDate(),manager.getListOfTrips().get(i).getPrice(),
            manager.getListOfTrips().get(i).getDriver().getId()});
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JTable getTripsTable() {
        return tripsTable;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerGUI().setVisible(true);
            }
        });
    }
    public static boolean makeTicket(Customer customer , boolean isRoundTrip)
    {
        Trip trip = customer.getTrip();
        try
        {
            File file = new File ("ticketTemplate.jpg");
            final BufferedImage image = ImageIO.read(file);
            Graphics g = image.getGraphics();
            g.setFont(g.getFont().deriveFont(30f));
            g.setColor(Color.BLACK);
            g.drawString("date", 145, 195);//date
            g.drawString(trip.getlocationFrom() + " to " + trip.getDestination(), 145, 278);//route
            g.drawString(trip.getlocationFrom(), 558, 278);//start
            g.drawString(trip.getDestination(), 947, 278);//depart
            g.drawString(customer.getNumOfSeats() + "", 145, 359);//seats
            g.drawString(customer.getFirstName() + " " + customer.getLastName(), 145, 449);//name
            g.drawString(customer.getPhoneNumber(), 861, 449);//phone
            g.drawString(customer.getCodeName(), 891, 363);//code name
            g.drawString(trip.getPrice() * customer.getNumOfSeats() * trip.calculateRoundTripPrice(isRoundTrip) + "", 549, 195);//price
            
            if (customer.isRoundTrip())
            {
                File checkimgfile = new File ("check-mark.png");
                final BufferedImage checkimg = ImageIO.read(checkimgfile);
                Image newImage = checkimg.getScaledInstance(40, 40, Image.SCALE_DEFAULT);
                g.drawImage(newImage, 891 , 165 , null);
            }
            else
            {
                File crossimgfile = new File ("x-mark.png");
                BufferedImage crossimg = ImageIO.read(crossimgfile);
                Image newImage = crossimg.getScaledInstance(40, 40, Image.SCALE_DEFAULT);
                g.drawImage(newImage, 891 , 165 , null);
            }
            g.dispose();
            ImageIO.write(image, "jpg", new File("ticket.jpg"));
            return true;
        }
        catch (FileNotFoundException e)
        {
            System.out.println("Ticket.jpg not found");
            e.printStackTrace();
        }
        catch (IOException e) {
            System.out.println("Error creating test.png");
            e.printStackTrace();
        }

        return false;
    }
    public static boolean makeTicket(String locationFrom , String destination , String firstName , String lastName
            , String price , String numOfSeats , String phoneNumber , String tripCodeName , boolean roundTrip)
    {
        try
        {
            File file = new File ("ticketTemplate.jpg");
            final BufferedImage image = ImageIO.read(file);
            Graphics g = image.getGraphics();
            g.setFont(g.getFont().deriveFont(30f));
            g.setColor(Color.BLACK);
            g.drawString("date", 145, 195);//date
            g.drawString(locationFrom + " to " + destination, 145, 278);//route
            g.drawString(locationFrom, 558, 278);//start
            g.drawString(destination, 947, 278);//depart
            g.drawString(numOfSeats, 145, 359);//seats
            g.drawString(firstName + " " + lastName, 145, 449);//name
            g.drawString(phoneNumber, 861, 449);//phone
            g.drawString(tripCodeName, 891, 363);//code name
            g.drawString(price, 549, 195);//price
            //g.drawString(roundTrip, 891, 195);//round trip
            if (roundTrip)
            {
                File checkimgfile = new File ("check-mark.png");
                final BufferedImage checkimg = ImageIO.read(checkimgfile);
                Image newImage = checkimg.getScaledInstance(40, 40, Image.SCALE_DEFAULT);
                g.drawImage(newImage, 891 , 165 , null);
            }
            else
            {
                File crossimgfile = new File ("x-mark.png");
                BufferedImage crossimg = ImageIO.read(crossimgfile);
                Image newImage = crossimg.getScaledInstance(40, 40, Image.SCALE_DEFAULT);
                g.drawImage(newImage, 891 , 165 , null);
            }
            g.dispose();
            ImageIO.write(image, "jpg", new File("ticket.jpg"));
            return true;
        }
        catch (FileNotFoundException e)
        {
            System.out.println("Ticket.jpg not found");
            e.printStackTrace();
        }
        catch (IOException e) {
            System.out.println("Error creating test.png");
            e.printStackTrace();
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel newPriceField;
    private javax.swing.JTextField numOfSeatsField;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JTable tripsTable;
    // End of variables declaration//GEN-END:variables

}
